"""Java-free OWL 2 DL reasoning over shared pyowl-core ontology views."""

from __future__ import annotations

from pyowl_core import (
    IRI,
    ImportResolver,
    LoadOptions,
    OntologyComposite,
    OntologyDelta,
    OntologyInput,
    OntologyOverlay,
    OntologySnapshot,
    OntologyView,
    apply_delta,
    compose_views,
    load_snapshot,
)

from ._version import __version__
from .backends.dispatch import NATIVE_ABI_VERSION
from .backends.protocol import (
    COMPILED_IR_SCHEMA_VERSION,
    BackendInfo,
    BackendStatus,
    Hierarchy,
)
from .config import (
    BackendName,
    BlockingMode,
    ExistentialMode,
    FreshEntityPolicy,
    IndividualGrouping,
    ReasonerConfig,
    UnsupportedDatatypePolicy,
)
from .core import COMPILER_CACHE_SCHEMA_VERSION
from .exceptions import (
    BackendError,
    BackendMismatchError,
    BackendPoisonedError,
    BackendVersionError,
    ConcurrentMutationError,
    DisposedReasonerError,
    FeatureNotImplementedError,
    FreshEntityError,
    IncompleteImportClosureError,
    InconsistentOntologyError,
    InternalInvariantError,
    InvalidLiteralError,
    NativeBackendUnavailableError,
    OntologyInputError,
    OntologyProfileError,
    PyHermiTError,
    ReasonerInterruptedError,
    ReasonerStateError,
    ReasonerTimeoutError,
    ReasoningAbortedError,
    ResourceLimitError,
    UnsupportedDatatypeError,
)
from .facade import InferenceType, Reasoner, backend_info

__all__ = [
    "COMPILED_IR_SCHEMA_VERSION",
    "COMPILER_CACHE_SCHEMA_VERSION",
    "IRI",
    "NATIVE_ABI_VERSION",
    "BackendError",
    "BackendInfo",
    "BackendMismatchError",
    "BackendName",
    "BackendPoisonedError",
    "BackendStatus",
    "BackendVersionError",
    "BlockingMode",
    "ConcurrentMutationError",
    "DisposedReasonerError",
    "ExistentialMode",
    "FeatureNotImplementedError",
    "FreshEntityError",
    "FreshEntityPolicy",
    "Hierarchy",
    "ImportResolver",
    "IncompleteImportClosureError",
    "InconsistentOntologyError",
    "IndividualGrouping",
    "InferenceType",
    "InternalInvariantError",
    "InvalidLiteralError",
    "LoadOptions",
    "NativeBackendUnavailableError",
    "OntologyComposite",
    "OntologyDelta",
    "OntologyInput",
    "OntologyInputError",
    "OntologyOverlay",
    "OntologyProfileError",
    "OntologySnapshot",
    "OntologyView",
    "PyHermiTError",
    "Reasoner",
    "ReasonerConfig",
    "ReasonerInterruptedError",
    "ReasonerStateError",
    "ReasonerTimeoutError",
    "ReasoningAbortedError",
    "ResourceLimitError",
    "UnsupportedDatatypeError",
    "UnsupportedDatatypePolicy",
    "__version__",
    "apply_delta",
    "backend_info",
    "compose_views",
    "load_snapshot",
]
