"""Pure-Python OWL 2 datatype values, facets, and family range algebra.

SPDX-License-Identifier: LGPL-3.0-or-later

The package is independent of tableau state, Java, and native runtimes.  It exposes
source-preserving literal compilation plus the completed built-in lexical/facet tranche;
mixed-family data-domain algebra and the later component solver remain separate WP07 work.
"""

from __future__ import annotations

from .binary import XSD_BASE64_BINARY, XSD_HEX_BINARY
from .facets import (
    RDF_LANG_RANGE,
    XSD_LENGTH,
    XSD_MAX_EXCLUSIVE,
    XSD_MAX_INCLUSIVE,
    XSD_MAX_LENGTH,
    XSD_MIN_EXCLUSIVE,
    XSD_MIN_INCLUSIVE,
    XSD_MIN_LENGTH,
    XSD_PATTERN,
    FacetRestriction,
    restrict_datatype,
)
from .ieee_ranges import IEEEInterval, IEEERange, IEEEValue
from .literals import (
    NUMERIC_DATATYPES,
    OWL_NAMESPACE,
    OWL_RATIONAL,
    OWL_REAL,
    RDFS_LITERAL,
    SUPPORTED_DATATYPES,
    XSD_BOOLEAN,
    XSD_DECIMAL,
    XSD_DOUBLE,
    XSD_FLOAT,
    XSD_INTEGER,
    XSD_NAMESPACE,
    NumericDatatypeSpec,
    compile_literal,
    numeric_datatype_spec,
)
from .model import (
    BinaryComparison,
    BinaryIdentity,
    BinaryKind,
    BooleanComparison,
    BooleanIdentity,
    ComparisonOrder,
    ComparisonValue,
    CompiledLiteral,
    DataIdentity,
    DatatypeLimits,
    DateTimeComparison,
    DateTimeIdentity,
    IEEECategory,
    IEEEComparison,
    IEEEFormat,
    IEEEIdentity,
    LexicalCompatibility,
    NumericComparison,
    NumericDomain,
    NumericIdentity,
    SourceLiteralIdentity,
    StringComparison,
    StringIdentity,
    URIComparison,
    URIIdentity,
    XMLComparison,
    XMLIdentity,
)
from .nonnumeric_ranges import (
    BinaryRange,
    BinaryValue,
    LengthInterval,
    LengthRange,
    LiteralRange,
    StringRange,
    StringValue,
    TextLanguageRectangle,
    URIRange,
    URIValue,
    XMLRange,
    XMLValue,
)
from .ranges import (
    BooleanRange,
    DatatypeRange,
    NumericInterval,
    NumericRange,
    RangeValue,
    numeric_domain_contains,
    range_for_datatype,
)
from .temporal import XSD_DATE_TIME, XSD_DATE_TIME_STAMP
from .temporal_ranges import DateTimeRange, DateTimeValue
from .textual import (
    RDF_NAMESPACE,
    RDF_PLAIN_LITERAL,
    STRING_DATATYPES,
    XSD_ANY_URI,
    XSD_LANGUAGE,
    XSD_NAME,
    XSD_NCNAME,
    XSD_NMTOKEN,
    XSD_NORMALIZED_STRING,
    XSD_STRING,
    XSD_TOKEN,
    StringDatatypeSpec,
    string_datatype_spec,
)
from .xml_literal import RDF_XML_LITERAL
from .xsd_regex import PINNED_UNICODE_VERSION, XML_CHARACTERS, CharSet, XSDRegex

__all__ = [
    "NUMERIC_DATATYPES",
    "OWL_NAMESPACE",
    "OWL_RATIONAL",
    "OWL_REAL",
    "PINNED_UNICODE_VERSION",
    "RDFS_LITERAL",
    "RDF_LANG_RANGE",
    "RDF_NAMESPACE",
    "RDF_PLAIN_LITERAL",
    "RDF_XML_LITERAL",
    "STRING_DATATYPES",
    "SUPPORTED_DATATYPES",
    "XML_CHARACTERS",
    "XSD_ANY_URI",
    "XSD_BASE64_BINARY",
    "XSD_BOOLEAN",
    "XSD_DATE_TIME",
    "XSD_DATE_TIME_STAMP",
    "XSD_DECIMAL",
    "XSD_DOUBLE",
    "XSD_FLOAT",
    "XSD_HEX_BINARY",
    "XSD_INTEGER",
    "XSD_LANGUAGE",
    "XSD_LENGTH",
    "XSD_MAX_EXCLUSIVE",
    "XSD_MAX_INCLUSIVE",
    "XSD_MAX_LENGTH",
    "XSD_MIN_EXCLUSIVE",
    "XSD_MIN_INCLUSIVE",
    "XSD_MIN_LENGTH",
    "XSD_NAME",
    "XSD_NAMESPACE",
    "XSD_NCNAME",
    "XSD_NMTOKEN",
    "XSD_NORMALIZED_STRING",
    "XSD_PATTERN",
    "XSD_STRING",
    "XSD_TOKEN",
    "BinaryComparison",
    "BinaryIdentity",
    "BinaryKind",
    "BinaryRange",
    "BinaryValue",
    "BooleanComparison",
    "BooleanIdentity",
    "BooleanRange",
    "CharSet",
    "ComparisonOrder",
    "ComparisonValue",
    "CompiledLiteral",
    "DataIdentity",
    "DatatypeLimits",
    "DatatypeRange",
    "DateTimeComparison",
    "DateTimeIdentity",
    "DateTimeRange",
    "DateTimeValue",
    "FacetRestriction",
    "IEEECategory",
    "IEEEComparison",
    "IEEEFormat",
    "IEEEIdentity",
    "IEEEInterval",
    "IEEERange",
    "IEEEValue",
    "LengthInterval",
    "LengthRange",
    "LexicalCompatibility",
    "LiteralRange",
    "NumericComparison",
    "NumericDatatypeSpec",
    "NumericDomain",
    "NumericIdentity",
    "NumericInterval",
    "NumericRange",
    "RangeValue",
    "SourceLiteralIdentity",
    "StringComparison",
    "StringDatatypeSpec",
    "StringIdentity",
    "StringRange",
    "StringValue",
    "TextLanguageRectangle",
    "URIComparison",
    "URIIdentity",
    "URIRange",
    "URIValue",
    "XMLComparison",
    "XMLIdentity",
    "XMLRange",
    "XMLValue",
    "XSDRegex",
    "compile_literal",
    "numeric_datatype_spec",
    "numeric_domain_contains",
    "range_for_datatype",
    "restrict_datatype",
    "string_datatype_spec",
]
