"""Deterministic private DL-clause IR and clausification entry points."""

from __future__ import annotations

from .compiler import (
    CLAUSIFICATION_HANDLER_TABLE,
    compile_captured,
    compile_delta_plan,
    compile_normalized,
    compile_query_program,
    compiled_schema_manifest,
)
from .model import (
    Atom,
    CanonicalRecord,
    ClauseProgram,
    CompilationLimits,
    CompiledDelta,
    CompiledQuery,
    DataConstant,
    DatatypeModelIR,
    DeltaCompatibility,
    DeltaFactIR,
    DLClause,
    Expressivity,
    GroundAtom,
    GroundDisjunctionIR,
    IndividualTerm,
    LiteralIdentityIR,
    Predicate,
    PredicateKind,
    PredicateRegistry,
    ProvenanceEntry,
    ProvenanceTable,
    RoleAutomatonIR,
    RoleModelIR,
    RoleTransitionIR,
    SymbolDomain,
    SymbolKind,
    SymbolTable,
    SymbolValue,
    TermSort,
    Variable,
    term_sort,
)

__all__ = [
    "CLAUSIFICATION_HANDLER_TABLE",
    "Atom",
    "CanonicalRecord",
    "ClauseProgram",
    "CompilationLimits",
    "CompiledDelta",
    "CompiledQuery",
    "DLClause",
    "DataConstant",
    "DatatypeModelIR",
    "DeltaCompatibility",
    "DeltaFactIR",
    "Expressivity",
    "GroundAtom",
    "GroundDisjunctionIR",
    "IndividualTerm",
    "LiteralIdentityIR",
    "Predicate",
    "PredicateKind",
    "PredicateRegistry",
    "ProvenanceEntry",
    "ProvenanceTable",
    "RoleAutomatonIR",
    "RoleModelIR",
    "RoleTransitionIR",
    "SymbolDomain",
    "SymbolKind",
    "SymbolTable",
    "SymbolValue",
    "TermSort",
    "Variable",
    "compile_captured",
    "compile_delta_plan",
    "compile_normalized",
    "compile_query_program",
    "compiled_schema_manifest",
    "term_sort",
]
